openapi: 3.1.0
info:
  title: GPT Gateway
  description: FastAPI middleware to list, read, write, and scan GitHub repositories for use in GPT Actions.
  version: 1.0.0
servers:
  - url: https://gpt-gateway-cigu.onrender.com
    description: Production server

paths:
  /list-files/:
    get:
      operationId: listFiles
      summary: List files in a GitHub repository path
      parameters:
        - name: owner
          in: query
          required: true
          schema:
            type: string
        - name: repo
          in: query
          required: true
          schema:
            type: string
        - name: path
          in: query
          required: false
          schema:
            type: string
        - name: branch
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success listing files
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  tree:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        path:
                          type: string
                        type:
                          type: string

  /read-file/:
    get:
      operationId: readFile
      summary: Read contents of a file from a GitHub repository
      parameters:
        - name: owner
          in: query
          required: true
          schema:
            type: string
        - name: repo
          in: query
          required: true
          schema:
            type: string
        - name: path
          in: query
          required: true
          schema:
            type: string
        - name: branch
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: File content returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  content:
                    type: string

  /write-file/:
    put:
      operationId: writeFile
      summary: Write or update a file in a GitHub repository
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                owner:
                  type: string
                repo:
                  type: string
                path:
                  type: string
                branch:
                  type: string
                  default: main
                content:
                  type: string
                message:
                  type: string
      responses:
        "200":
          description: File written successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /scan-repo/:
    post:
      operationId: scanRepo
      summary: Recursively scan a GitHub repository path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                owner:
                  type: string
                repo:
                  type: string
                path:
                  type: string
                branch:
                  type: string
                depth:
                  type: integer
                  default: 5
      responses:
        "200":
          description: Recursive structure returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  tree:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        path:
                          type: string
                        type:
                          type: string
